word_list = {"apple": "A fruit that keeps the doctor away!",
"pineapple":"A juicy,edible tropical fruit somewhat resembling a pine cone!",
"banana":"A curved,yellow fruit with a thick skin and soft flesh!",
"papaya":"A large fleshy berry with smooth green skin that ripens to yellow and orange!",
"pomgranate":"A fruit that is called apple with many seeds!",
"strawberry":"A fruit which is bright red,juicy and an excellent source of vitamin C!",
"guvava":"A round pear shaped fruit which has many seeds inside!",
"kiwi":"A fruit which has furry brownish green skin with tiny black edible seeds inside!",
"coconut":" A fruit which has a hard shell, edible white flesh and clear liquid!",
"orange":"A Round and citrus fruit , it is fruit as well as color!",
"mango":"A fruit which is known as King of Fruits!",
"lemon":"An oval citrus fruit with smooth porous skin!",
"watermelon":"A large, oval fruit with green skin, sweet, juicy pulp; and seeds!",
"apricot":"A small stone Fruit, appears like small peach!",
"almond":" A bright white fruti and wrapped in a reddish brown cover!",
"avocado":"A bright green fruit with a large pit and dark leathery skin!",
"blackberry":" Identified as it is juicy, black, and belongs to berries!",
"blueberry":" It is juicy, blue, and belongs to berries!",
"cherry":"A small, round fruit that can be sweet or sour!",
"custardapple": " A green, cone-shaped fruit with leathery skin and creamy, sweet flesh with seeds inside!",
"dragonfruit":"A fruit which is also known as 'pitaya' !",
"grapes":"A small, round fruit, usually pale green, purple, or red, that grows on a vine or used for making wine!",
"grapefruit":"A large, round, yellow fruit, similar to an orange, that has a sharp, slightly bitter taste!",
"lychee":"A fruit which is sweet, with slightly floral and acidic notes!",
"mulberry":"Colorful berries that are eaten both fresh and dried!",
"pear":"A sweet, juicy fruit which is narrow near its stalk, and wider and rounded at the bottom!",
"peach":"A soft, round, slightly furry fruit with sweet yellow flesh and pinky-orange skin!",
"cashew":"A soft, round, slightly furry fruit with sweet yellow flesh and pinky-orange skin!",
"pistachio":" A drupe, containing an elongated seed, which is the edible portio!",
"plum":" A small, dark reddish purple, and sweet which have an edible, smooth skin, juicy flesh, and a hard pit in the middle!",
"rasins":"A dehydrated or sun-dried grape!",
"sapota":"An oval or round shape fruit with brown skin!",
"muskmelon":" A tender, warm-weather vegetable that requires culture similar to that of cucumbers!",
"raspbeery":"A small, conical or round fruit with a velvety red or yellowish skin!",
"dates":"A one-seeded fruit, or drupe, usually oblong but varying much in shape, size, colour, quality, and consistency of flesh!",
"pineberry":" A white strawberry with red seeds with pineapple overtones!",
"almonds":" A drupe, consisting of an outer hull and a hard shell with the seed!",
"olivefruit":"A drupe, similar to the peach or plum!",
"tamarind":"A sweet and sour fruit that grows in pods!",
"blackcurrent":" a berry of translucent pulp with red or green tones and bittersweet taste!",
"cranberry":"A small, hard, round, red fruits with a flavor that many describe as both bitter and sour!",
             }
